package br.unicesumar.onefreela.dto;

public enum ErrorCode {

    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    INTERNAL_SERVER_ERROR,

    WRONG_LOGIN_CREDENTIALS,

    TOKEN_NOT_FOUND,
    EMAIL_INVALID,
    EMAIL_REQUIRED,
    EMAIL_TOO_LONG,
    EMAIL_TOO_SHORT,
    EMAIL_ALREADY_EXISTS,
    EMAIL_DOES_NOT_EXIST,

    PASSWORD_INVALID,
    PASSWORD_REQUIRED,
    PASSWORD_TOO_SHORT,
    PASSWORD_TOO_LONG,
    PASSWORD_LACK_NUMBER,
    PASSWORD_LACK_UPPERCASE,
    PASSWORD_LACK_SPECIAL_CHAR,

    NAME_INVALID,
    NAME_REQUIRED,
    NAME_TOO_LONG,
    NAME_TOO_SHORT,
    NAME_HAS_NUMBER,
    NAME_HAS_SPECIAL_CHAR,

    PHONE_NUMBER_INVALID,
    PHONE_NUMBER_REQUIRED,
    PHONE_NUMBER_TOO_LONG,
    PHONE_NUMBER_TOO_SHORT,
    PHONE_NUMBER_HAS_LETTER,

    CPF_INVALID,
    CPF_REQUIRED,
    CPF_TOO_LONG,
    CPF_TOO_SHORT,
    CPF_HAS_LETTER,
    CPF_HAS_ONLY_EQUAL_NUMBERS,

    BIRTHDAY_INVALID,
    BIRTHDAY_REQUIRED,
    BIRTHDAY_IN_FUTURE,
    BIRTHDAY_TOO_OLD,
    BIRTHDAY_TOO_RECENT,

    INVALID_CREDENTIALS,
    TOKEN_EXPIRED,
    ACCESS_DENIED,

    WORK_NOT_FOUND,
    WORK_TITLE_REQUIRED,
    WORK_TITLE_TOO_SHORT,
    WORK_TITLE_TOO_LONG,
    WORK_DESCRIPTION_REQUIRED,
    WORK_DESCRIPTION_TOO_SHORT,
    WORK_DESCRIPTION_TOO_LONG,
    WORK_CATEGORY_REQUIRED,
    WORK_CATEGORY_TOO_LONG,
    WORK_PRICE_REQUIRED,
    WORK_PRICE_INVALID,
    WORK_PRICE_RANGE_INVALID,
    WORK_CANNOT_BE_DELETED,
    FREELANCER_REQUIRED,

    ORDER_NOT_FOUND,
    ORDER_ALREADY_PAID,
    ORDER_NOT_PAID,
    ORDER_ALREADY_REFUNDED,
    ORDER_CANNOT_BE_REFUNDED,

    ORDER_ITEM_NOT_FOUND,
    ORDER_ITEM_ALREADY_COMPLETED,
    ORDER_ITEM_NOT_IN_PROGRESS,
    ORDER_ITEM_CANNOT_BE_COMPLETED,

    INSUFFICIENT_BALANCE,
    PAYMENT_FAILED,
    WORK_BELONGS_TO_CLIENT,
    WORK_INACTIVE,
}