package br.unicesumar.onefreela.dto;

public enum ErrorCode {

    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    INTERNAL_SERVER_ERROR,

    EMAIL_INVALID,
    EMAIL_REQUIRED,
    EMAIL_TOO_LONG,
    EMAIL_TOO_SHORT,
    EMAIL_ALREADY_EXISTS,

    PASSWORD_INVALID,
    PASSWORD_REQUIRED,
    PASSWORD_TOO_SHORT,
    PASSWORD_TOO_LONG,
    PASSWORD_LACK_NUMBER,
    PASSWORD_LACK_UPPERCASE,
    PASSWORD_LACK_SPECIAL_CHAR,

    NAME_INVALID,
    NAME_REQUIRED,
    NAME_TOO_LONG,
    NAME_TOO_SHORT,
    NAME_HAS_NUMBER,
    NAME_HAS_SPECIAL_CHAR,

    PHONE_NUMBER_INVALID,
    PHONE_NUMBER_REQUIRED,
    PHONE_NUMBER_TOO_LONG,
    PHONE_NUMBER_TOO_SHORT,
    PHONE_NUMBER_HAS_LETTER,

    CPF_INVALID,
    CPF_REQUIRED,
    CPF_TOO_LONG,
    CPF_TOO_SHORT,
    CPF_HAS_LETTER,
    CPF_HAS_ONLY_EQUAL_NUMBERS,

    BIRTHDAY_INVALID,
    BIRTHDAY_REQUIRED,
    BIRTHDAY_IN_FUTURE,
    BIRTHDAY_TOO_OLD,
    BIRTHDAY_TOO_RECENT,

    INVALID_CREDENTIALS,
    TOKEN_EXPIRED,
    ACCESS_DENIED,
}
