package br.unicesumar.onefreela.enums;

public enum MessageType {
    TEXT,
    ATTACHMENT,
    DELIVERY,
    DELIVERY_ACCEPTED,
    DELIVERY_REFUSED,
    ADJUSTMENT_ACCEPTED,
    ADJUSTMENT_REFUSED,
    DISPUTE_OPENED,
    DISPUTE_RESOLVED_FREELANCER,
    DISPUTE_RESOLVED_CLIENT,
    DELIVERY_ACCEPTED_AFTER_FREEZE
}