spring.application.name=onefreela
spring.datasource.url=jdbc:mysql://localhost:3306/onefreeladb?allowPublicKeyRetrieval=true&useSSL=false
spring.data.redis.host=localhost
spring.data.redis.port=6379

app.upload.report-dir=uploads/reports