spring.datasource.username=root
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

app.upload.report-dir=uploads/reports
app.upload.delivery-dir=uploads/deliveries
app.upload.chat-dir=uploads/chat